services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
      - SQLITE_DB_FILE=/workspace/run/data/ai_gateway.db
      - LOG_DIR=/workspace/run/logs
      - STATIC_DIR=/workspace/web/static
      - TEMPLATE_DIR=/workspace/web/templates
    command: sleep infinity
    depends_on:
      - redis
    networks:
      - devcontainer

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - devcontainer

volumes:
  redis_data:

networks:
  devcontainer:
    driver: bridge
