version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REDIS_ADDR=redis:6379
      - PORT=8080
      - SQLITE_DB_PATH=/workspace/data/ai_gateway.db
      - LOG_DIR=/workspace/logs
      - STATIC_DIR=/workspace/web/static
      - TEMPLATE_DIR=/workspace/web/templates
    command: sleep infinity
    depends_on:
      - redis
    networks:
      - aigwhub

  redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - aigwhub

volumes:
  redis_data:

networks:
  aigwhub:
    driver: bridge